# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Global exclusion patterns
exclude: '^(knowledge_base/|large_files_for_dropbox_download/|\.windsurf/|\.cursor/|\.idea/)'

repos:
  # --- Foundational hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ['--unsafe']  # Allow custom tags
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1024']
      # These hooks will be skipped in CI to prevent modification issues
      - id: end-of-file-fixer
        stages: [commit]  # Only run locally
      - id: trailing-whitespace
        stages: [commit]  # Only run locally
      - id: mixed-line-ending
        args: ['--fix=lf']

  # --- Python: Ruff (fast, replaces Black/isort/flake8) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.8
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '^(phases/01_LegacyDB/infrastructure/)'
      - id: ruff-format
        exclude: '^(phases/01_LegacyDB/infrastructure/)'

  # --- Jupyter Notebooks ---
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [--max-size, '1000']  # Strip outputs from cells > 1KB

  # --- SQL Formatting ---
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres]
        files: \.sql$
        exclude: '^(infrastructure/db/legacy_db_sql_scripts/TMP_.*\.sql)'
      # Fix hook only runs locally
      - id: sqlfluff-fix
        stages: [commit]
        args: [--dialect, postgres]
        files: \.sql$
        exclude: '^(infrastructure/db/legacy_db_sql_scripts/TMP_.*\.sql)'

  # --- Security: Detect Secrets ---
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude_types: [pdf, png, jpeg, jpg, tif, tiff, epub]
